### ISSUE TITLE
Plaid issue: Jonh Hancock Transactions

### ISSUE THREAD

**Issue by smiley717** [Clarifees/income-sample#1]
![image](https://github.com/Clarifees/income-sample/assets/80674675/e245606a-88e0-4328-a57f-c74b488391ff)

@devcopter9111  @leninhernandez 
They are working on it and I am thinking about release 3.3 this week once get one.

**Comment by devcopter9111** [comment]
@smiley717 @leninhernandez 
lgtm. but parsing is difficult a little.
Is it able to be more readable and parsable?
